FeatureToggle/__init__.py, UnleashClient/strategies/EnableForDomainStrategy.py
Add method to fetch toggles from cache
=> Add method to fetch toggles from cache and update domain strategy

UnleashClient/strategies/EnableForDomainStrategy.py
Use domain names instead of domain ids
=> Use domain names instead of domain ids

unleash-client-python/FeatureToggle/__init__.py, unleash-client-python/UnleashClient/loader.py, unleash-client-python/UnleashClient/periodic_tasks/fetch_and_load.py
=> Refactor the fetch_feature_toggles util method's parsing logic

unleash-client-python/FeatureToggle/__init__.py, unleash-client-python/UnleashClient/__init__.py
Remove first api call on initialisation
=> Remove first api call on SDK initialisation

unleash-client-python/FeatureToggle/__init__.py
Please include a summary of the change and which issue is fixed (if any).
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes.
=> Remove the CAS Name and ENV

unleash-client-python/UnleashClient/__init__.py, unleash-client-python/UnleashClient/periodic_tasks/fetch_and_load.py
Load features at the time of initialisation
=> Load features at the time of initialisation

unleash-client-python/FeatureToggle/__init__.py
Fix the indentation.
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes.
=> Fix the indentation

unleash-client-python/FeatureToggle/__init__.py
Please include a summary of the change and which issue is fixed (if any).
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes.
=> Replace variables

.github/PULL_REQUEST_TEMPLATE.md, .github/codecov.yml, .github/mergeable.yml, .github/release-drafter.yml
1. Add Mergeable
2. Add Release drafter
3. Add code coverage
=> Add repo checks

FeatureToggles/__init__.py
JIRA TICKET: 
Refactor the feature toggle module
=> Refactor feature toggle module

FeatureToggle/__init__.py, README.md
JIRA TICKET: 
Add readme file and rename directory name
=> Add readme file and rename directory name

FeatureToggle/__init__.py, UnleashClient/__init__.py, UnleashClient/strategies/EnableForBusinessStrategy.py, UnleashClient/strategies/EnableForDomainStrategy.py, UnleashClient/strategies/EnableForExpertStrategy.py, UnleashClient/strategies/EnableForPartnerStrategy.py, UnleashClient/strategies/EnableForTeamStrategy.py, UnleashClient/utils.py
https://hello-haptik.atlassian.net/browse/AGCT-1509
=> enhance(Strategy): Add Team ID based strategy

.github/PULL_REQUEST_TEMPLATE.md, .github/codecov.yml, .github/mergeable.yml, .github/release-drafter.yml, FeatureToggle/__init__.py, UnleashClient/constants.py, UnleashClient/strategies/EnableForDomainStrategy.py, requirements-dev.txt, requirements-local.txt, requirements.txt, setup.py, unleash-client-python/UnleashClient/__init__.py, unleash-client-python/UnleashClient/loader.py, unleash-client-python/UnleashClient/strategies/EnableForBusinessStrategy.py, unleash-client-python/UnleashClient/strategies/EnableForExpertStrategy.py, unleash-client-python/UnleashClient/strategies/EnableForPartnerStrategy.py, unleash-client-python/UnleashClient/strategies/EnableForTeamStrategy.py, unleash-client-python/UnleashClient/utils.py
JIRA TICKET: https://hello-haptik.atlassian.net/browse/BB-7207
(REMOVE ME) Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> develop -> master

FeatureToggle/__init__.py, FeatureToggle/utils.py, UnleashClient/utils.py
JIRA TICKET:   https://hello-haptik.atlassian.net/browse/BB-7596
Added Clear LRU cache function
=> LRU cache added for feature toggles

FeatureToggle/__init__.py
JIRA TICKET:  https://hello-haptik.atlassian.net/browse/BB-7596
(REMOVE ME) Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> Remove unwanted imports

FeatureToggle/__init__.py, FeatureToggle/utils.py, UnleashClient/utils.py
JIRA TICKET:  https://hello-haptik.atlassian.net/browse/BB-7596
cache info logger added
=> cache info logger added

FeatureToggle/__init__.py, FeatureToggle/utils.py, UnleashClient/utils.py
JIRA TICKET: 
(REMOVE ME) Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> Develop-> master release

FeatureToggle/__init__.py
JIRA TICKET: GRAVEYARD-1171
Check if data was properly saved in redis
=> Check if data was properly saved in redis

FeatureToggle/__init__.py
JIRA TICKET: https://hello-haptik.atlassian.net/browse/BB-7914
(REMOVE ME) Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> Return empty response from Feature Toggles Library if redis is down

requirements-dev.txt, requirements-local.txt, requirements.txt
JIRA TICKET: https://hello-haptik.atlassian.net/browse/IS-677
Upgrading mkdocs package
=> upgrading mkdocs package

FeatureToggle/__init__.py, requirements-dev.txt, requirements-local.txt, requirements.txt
JIRA TICKET: https://hello-haptik.atlassian.net/browse/IS-677
=> Develop to Master
